SET FOREIGN_KEY_CHECKS = 0;
delete from borrowers where flags is null;
delete from borrower_message_preferences where borrowernumber is not null;
truncate user_permissions;
truncate patroncards;
truncate patronimage;
truncate borrower_attributes;
truncate action_logs; 
truncate aqorders; 
truncate aqorderdelivery;
truncate branchtransfers;
truncate tmp_holdsqueue; 
truncate deleteditems; 
truncate deletedbiblioitems; 
truncate deletedbiblio; 
truncate deletedborrowers;
truncate import_batches;         
truncate import_biblios;         
truncate import_items;          
truncate import_record_matches; 
truncate import_records;
truncate issues; 
truncate old_issues; 
truncate reserves; 
truncate old_reserves;  
truncate statistics;  
truncate accountlines; 
truncate reviews; 
truncate serial; 
truncate subscription; 
truncate subscriptionhistory; 
truncate subscriptionroutinglist; 
truncate virtualshelves; 
truncate virtualshelfcontents;  
truncate auth_header;
truncate zebraqueue; 
truncate items; 
truncate biblioitems; 
truncate biblio;
SET FOREIGN_KEY_CHECKS = 1;
