INSERT INTO branches (branchcode,branchname) VALUES('MAIN','MAIN');
INSERT INTO itemtypes (itemtype,description) VALUES('
?F%???¯???*??'?J^~EO??~?~V','
?F%???¯???*??'?J^~EO??~?~V');
INSERT INTO itemtypes (itemtype,description) VALUES('2','2');
INSERT INTO itemtypes (itemtype,description) VALUES('3 1/2x4','3 1/2x4');
INSERT INTO itemtypes (itemtype,description) VALUES('3.75 x 6 Glass Negative','3.75 x 6 Glass Negative');
INSERT INTO itemtypes (itemtype,description) VALUES('35 mm','35 mm');
INSERT INTO itemtypes (itemtype,description) VALUES('35 mm negative','35 mm negative');
INSERT INTO itemtypes (itemtype,description) VALUES('35mm','35mm');
INSERT INTO itemtypes (itemtype,description) VALUES('35mm negatives','35mm negatives');
INSERT INTO itemtypes (itemtype,description) VALUES('3x4.5 sepia photo','3x4.5 sepia photo');
INSERT INTO itemtypes (itemtype,description) VALUES('4x6','4x6');
INSERT INTO itemtypes (itemtype,description) VALUES('8x9.5','8x9.5');
INSERT INTO itemtypes (itemtype,description) VALUES('Ag-1','Ag-1');
INSERT INTO itemtypes (itemtype,description) VALUES('Alb-006','Alb-006');
INSERT INTO itemtypes (itemtype,description) VALUES('Album','Album');
INSERT INTO itemtypes (itemtype,description) VALUES('Annie & Kris Pedersen','Annie & Kris Pedersen');
INSERT INTO itemtypes (itemtype,description) VALUES('Archival print','Archival print');
INSERT INTO itemtypes (itemtype,description) VALUES('B&W Photo','B&W Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('B&W Photograph','B&W Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('B&W photo','B&W photo');
INSERT INTO itemtypes (itemtype,description) VALUES('B/Phootograph','B/Phootograph');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Copy Glossy','B/W Copy Glossy');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Film','B/W Film');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Framed Photograph','B/W Framed Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Negative','B/W Negative');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Photgraph','B/W Photgraph');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Photo','B/W Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Photo Copy','B/W Photo Copy');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Photo postcard','B/W Photo postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Photograph','B/W Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Photograph News Paper Photo','B/W Photograph News Paper Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Photogrpah','B/W Photogrpah');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Phtograph','B/W Phtograph');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Postcard','B/W Postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W Slide','B/W Slide');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W neg','B/W neg');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W negative','B/W negative');
INSERT INTO itemtypes (itemtype,description) VALUES('B/W photograph','B/W photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('B/w photo','B/w photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Baird','Baird');
INSERT INTO itemtypes (itemtype,description) VALUES('Black/White Photo','Black/White Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('CVP 1','CVP 1');
INSERT INTO itemtypes (itemtype,description) VALUES('Carte de viste and tintypes','Carte de viste and tintypes');
INSERT INTO itemtypes (itemtype,description) VALUES('Cepia','Cepia');
INSERT INTO itemtypes (itemtype,description) VALUES('Cepia photo','Cepia photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Christmas Card','Christmas Card');
INSERT INTO itemtypes (itemtype,description) VALUES('Color Photo','Color Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Color Photograph','Color Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Color Post Card','Color Post Card');
INSERT INTO itemtypes (itemtype,description) VALUES('Color Postcard','Color Postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('Color Slide','Color Slide');
INSERT INTO itemtypes (itemtype,description) VALUES('Color Slides','Color Slides');
INSERT INTO itemtypes (itemtype,description) VALUES('Color Sllide','Color Sllide');
INSERT INTO itemtypes (itemtype,description) VALUES('Color photo','Color photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Color photo.','Color photo.');
INSERT INTO itemtypes (itemtype,description) VALUES('Color slide','Color slide');
INSERT INTO itemtypes (itemtype,description) VALUES('Colored Photograph','Colored Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Colored Print','Colored Print');
INSERT INTO itemtypes (itemtype,description) VALUES('Copy','Copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Copy Photograph','Copy Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Copy of Ambrotype','Copy of Ambrotype');
INSERT INTO itemtypes (itemtype,description) VALUES('Copy of Tintype','Copy of Tintype');
INSERT INTO itemtypes (itemtype,description) VALUES('Copy of painting, by Hougart','Copy of painting, by Hougart');
INSERT INTO itemtypes (itemtype,description) VALUES('Cottonwood','Cottonwood');
INSERT INTO itemtypes (itemtype,description) VALUES('Document','Document');
INSERT INTO itemtypes (itemtype,description) VALUES('Drawing','Drawing');
INSERT INTO itemtypes (itemtype,description) VALUES('ED-6','ED-6');
INSERT INTO itemtypes (itemtype,description) VALUES('Film','Film');
INSERT INTO itemtypes (itemtype,description) VALUES('Film b/w vert.','Film b/w vert.');
INSERT INTO itemtypes (itemtype,description) VALUES('Film, negative','Film, negative');
INSERT INTO itemtypes (itemtype,description) VALUES('Film; B/W:Rect. Horiz. Card re-typed.','Film; B/W:Rect. Horiz. Card re-typed.');
INSERT INTO itemtypes (itemtype,description) VALUES('From newspaper','From newspaper');
INSERT INTO itemtypes (itemtype,description) VALUES('Glass negative','Glass negative');
INSERT INTO itemtypes (itemtype,description) VALUES('Glossy Photo','Glossy Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Glossy Photograph','Glossy Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Hardboard','Hardboard');
INSERT INTO itemtypes (itemtype,description) VALUES('Lantern Slide','Lantern Slide');
INSERT INTO itemtypes (itemtype,description) VALUES('Lg. Neg.','Lg. Neg.');
INSERT INTO itemtypes (itemtype,description) VALUES('Lg. Neg. 3','Lg. Neg. 3');
INSERT INTO itemtypes (itemtype,description) VALUES('Lith. copy','Lith. copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Lithograph','Lithograph');
INSERT INTO itemtypes (itemtype,description) VALUES('M-1','M-1');
INSERT INTO itemtypes (itemtype,description) VALUES('Magazine Clipping','Magazine Clipping');
INSERT INTO itemtypes (itemtype,description) VALUES('Mammoth Mine','Mammoth Mine');
INSERT INTO itemtypes (itemtype,description) VALUES('McCloud','McCloud');
INSERT INTO itemtypes (itemtype,description) VALUES('NONE','NONE');
INSERT INTO itemtypes (itemtype,description) VALUES('Neg','Neg');
INSERT INTO itemtypes (itemtype,description) VALUES('Neg & contact prints only','Neg & contact prints only');
INSERT INTO itemtypes (itemtype,description) VALUES('Neg 006; print','Neg 006; print');
INSERT INTO itemtypes (itemtype,description) VALUES('Neg 35mm','Neg 35mm');
INSERT INTO itemtypes (itemtype,description) VALUES('Neg only','Neg only');
INSERT INTO itemtypes (itemtype,description) VALUES('Neg,','Neg,');
INSERT INTO itemtypes (itemtype,description) VALUES('Neg.','Neg.');
INSERT INTO itemtypes (itemtype,description) VALUES('Neg.,','Neg.,');
INSERT INTO itemtypes (itemtype,description) VALUES('Neg., Photo','Neg., Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Negativ','Negativ');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative','Negative');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative  Also  Lg. Neg.','Negative  Also  Lg. Neg.');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative &  Photo','Negative &  Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative & Copy','Negative & Copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative & Photograph','Negative & Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative & copy','Negative & copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative (copy)','Negative (copy)');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative 35 mm','Negative 35 mm');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative Print','Negative Print');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative and photo','Negative and photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative of postcard','Negative of postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative print','Negative print');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative, Copy','Negative, Copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative, Copy Roll #7','Negative, Copy Roll #7');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative, Postcard','Negative, Postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative, Print','Negative, Print');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative, copy','Negative, copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative, print','Negative, print');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative,Copy','Negative,Copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative/Photo','Negative/Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative; print','Negative; print');
INSERT INTO itemtypes (itemtype,description) VALUES('Negative; print, Photograph','Negative; print, Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Negatives','Negatives');
INSERT INTO itemtypes (itemtype,description) VALUES('Negatives 35mm','Negatives 35mm');
INSERT INTO itemtypes (itemtype,description) VALUES('No photo','No photo');
INSERT INTO itemtypes (itemtype,description) VALUES('None','None');
INSERT INTO itemtypes (itemtype,description) VALUES('Obituary','Obituary');
INSERT INTO itemtypes (itemtype,description) VALUES('Ohotograph','Ohotograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Orig.','Orig.');
INSERT INTO itemtypes (itemtype,description) VALUES('Original','Original');
INSERT INTO itemtypes (itemtype,description) VALUES('Original Postcard','Original Postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('Original postcard','Original postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('P1','P1');
INSERT INTO itemtypes (itemtype,description) VALUES('P;hoto','P;hoto');
INSERT INTO itemtypes (itemtype,description) VALUES('PHOTO','PHOTO');
INSERT INTO itemtypes (itemtype,description) VALUES('PL1','PL1');
INSERT INTO itemtypes (itemtype,description) VALUES('People','People');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo','Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo    2 copies','Photo    2 copies');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo  (copy)','Photo  (copy)');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo - Post card','Photo - Post card');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo - copy','Photo - copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo - postcard','Photo - postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo Copy','Photo Copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo Copy On Paper','Photo Copy On Paper');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo Copy on Paper','Photo Copy on Paper');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo Tin','Photo Tin');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo copy','Photo copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo copy on paper','Photo copy on paper');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo copy/ID's','Photo copy/ID's');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo copy/negative','Photo copy/negative');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo in Oval','Photo in Oval');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo original & Copy','Photo original & Copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo postcard','Photo postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('Photo, copy','Photo, copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photogaph','Photogaph');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph','Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph  copy','Photograph  copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph & Neg','Photograph & Neg');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph & Neg.','Photograph & Neg.');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph (Copy)','Photograph (Copy)');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph (copy)','Photograph (copy)');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph -Copy','Photograph -Copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph Orginal & Copy','Photograph Orginal & Copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph album Bass','Photograph album Bass');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph of pencil drawing','Photograph of pencil drawing');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph sepia','Photograph sepia');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph, also slides','Photograph, also slides');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph, copy','Photograph, copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph-Postcard','Photograph-Postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('Photograph/ copy','Photograph/ copy');
INSERT INTO itemtypes (itemtype,description) VALUES('Photographer','Photographer');
INSERT INTO itemtypes (itemtype,description) VALUES('Photographs','Photographs');
INSERT INTO itemtypes (itemtype,description) VALUES('Photogrph','Photogrph');
INSERT INTO itemtypes (itemtype,description) VALUES('Photogrqaph','Photogrqaph');
INSERT INTO itemtypes (itemtype,description) VALUES('Photogrqph','Photogrqph');
INSERT INTO itemtypes (itemtype,description) VALUES('Photohgraph','Photohgraph');
INSERT INTO itemtypes (itemtype,description) VALUES('Photoraph','Photoraph');
INSERT INTO itemtypes (itemtype,description) VALUES('Phototgraph','Phototgraph');
INSERT INTO itemtypes (itemtype,description) VALUES('Pioneer Hanging File','Pioneer Hanging File');
INSERT INTO itemtypes (itemtype,description) VALUES('Pioneer Hanging file','Pioneer Hanging file');
INSERT INTO itemtypes (itemtype,description) VALUES('Pioneer Haning File','Pioneer Haning File');
INSERT INTO itemtypes (itemtype,description) VALUES('Pnotograph','Pnotograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Portrait','Portrait');
INSERT INTO itemtypes (itemtype,description) VALUES('Portrait photo','Portrait photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Post Card','Post Card');
INSERT INTO itemtypes (itemtype,description) VALUES('Post card','Post card');
INSERT INTO itemtypes (itemtype,description) VALUES('Postcard','Postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('Postcard (used)','Postcard (used)');
INSERT INTO itemtypes (itemtype,description) VALUES('Poster','Poster');
INSERT INTO itemtypes (itemtype,description) VALUES('Pphoto','Pphoto');
INSERT INTO itemtypes (itemtype,description) VALUES('Print','Print');
INSERT INTO itemtypes (itemtype,description) VALUES('Print (copy from negative)','Print (copy from negative)');
INSERT INTO itemtypes (itemtype,description) VALUES('Remembrance Card','Remembrance Card');
INSERT INTO itemtypes (itemtype,description) VALUES('Ruins, Old Shasta.','Ruins, Old Shasta.');
INSERT INTO itemtypes (itemtype,description) VALUES('Sepia','Sepia');
INSERT INTO itemtypes (itemtype,description) VALUES('Sepia Photograph','Sepia Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Sepia Postcard','Sepia Postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('Sepia photo','Sepia photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Sepia photograph','Sepia photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Shasta','Shasta');
INSERT INTO itemtypes (itemtype,description) VALUES('Sketch  Photo','Sketch  Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Sldie color','Sldie color');
INSERT INTO itemtypes (itemtype,description) VALUES('Slide','Slide');
INSERT INTO itemtypes (itemtype,description) VALUES('Slide  Color','Slide  Color');
INSERT INTO itemtypes (itemtype,description) VALUES('Slide  color','Slide  color');
INSERT INTO itemtypes (itemtype,description) VALUES('Slide Color','Slide Color');
INSERT INTO itemtypes (itemtype,description) VALUES('Slide cabinet files','Slide cabinet files');
INSERT INTO itemtypes (itemtype,description) VALUES('Slide color','Slide color');
INSERT INTO itemtypes (itemtype,description) VALUES('Slide color glass','Slide color glass');
INSERT INTO itemtypes (itemtype,description) VALUES('Smith','Smith');
INSERT INTO itemtypes (itemtype,description) VALUES('Smith yard','Smith yard');
INSERT INTO itemtypes (itemtype,description) VALUES('Snapshot','Snapshot');
INSERT INTO itemtypes (itemtype,description) VALUES('Square unmounted','Square unmounted');
INSERT INTO itemtypes (itemtype,description) VALUES('Studio','Studio');
INSERT INTO itemtypes (itemtype,description) VALUES('Studio photo','Studio photo');
INSERT INTO itemtypes (itemtype,description) VALUES('Studio photograph','Studio photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('Studio portrait','Studio portrait');
INSERT INTO itemtypes (itemtype,description) VALUES('Tintype','Tintype');
INSERT INTO itemtypes (itemtype,description) VALUES('Unknown','Unknown');
INSERT INTO itemtypes (itemtype,description) VALUES('Wedding Certificate','Wedding Certificate');
INSERT INTO itemtypes (itemtype,description) VALUES('Yellowed','Yellowed');
INSERT INTO itemtypes (itemtype,description) VALUES('Yellowed photograph','Yellowed photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('alb-006','alb-006');
INSERT INTO itemtypes (itemtype,description) VALUES('b/w copy','b/w copy');
INSERT INTO itemtypes (itemtype,description) VALUES('b/w photo','b/w photo');
INSERT INTO itemtypes (itemtype,description) VALUES('b/w photo postcard','b/w photo postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('b/w photograph','b/w photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('cloth flag','cloth flag');
INSERT INTO itemtypes (itemtype,description) VALUES('color photo','color photo');
INSERT INTO itemtypes (itemtype,description) VALUES('color photograph','color photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('color postcard','color postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('copy','copy');
INSERT INTO itemtypes (itemtype,description) VALUES('copy of Photograph','copy of Photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('dup. of photo SHS1976.17.27 Box Gen','dup. of photo SHS1976.17.27 Box Gen');
INSERT INTO itemtypes (itemtype,description) VALUES('duplicates of photo','duplicates of photo');
INSERT INTO itemtypes (itemtype,description) VALUES('files color','files color');
INSERT INTO itemtypes (itemtype,description) VALUES('film b/w vertical','film b/w vertical');
INSERT INTO itemtypes (itemtype,description) VALUES('loan','loan');
INSERT INTO itemtypes (itemtype,description) VALUES('neg','neg');
INSERT INTO itemtypes (itemtype,description) VALUES('neg.','neg.');
INSERT INTO itemtypes (itemtype,description) VALUES('negative','negative');
INSERT INTO itemtypes (itemtype,description) VALUES('negative.','negative.');
INSERT INTO itemtypes (itemtype,description) VALUES('negative/Photo','negative/Photo');
INSERT INTO itemtypes (itemtype,description) VALUES('negative; print','negative; print');
INSERT INTO itemtypes (itemtype,description) VALUES('negatives','negatives');
INSERT INTO itemtypes (itemtype,description) VALUES('nesgative; print','nesgative; print');
INSERT INTO itemtypes (itemtype,description) VALUES('no photo','no photo');
INSERT INTO itemtypes (itemtype,description) VALUES('none','none');
INSERT INTO itemtypes (itemtype,description) VALUES('phogograph','phogograph');
INSERT INTO itemtypes (itemtype,description) VALUES('photo','photo');
INSERT INTO itemtypes (itemtype,description) VALUES('photo b/w','photo b/w');
INSERT INTO itemtypes (itemtype,description) VALUES('photo copy','photo copy');
INSERT INTO itemtypes (itemtype,description) VALUES('photo negative','photo negative');
INSERT INTO itemtypes (itemtype,description) VALUES('photo postcard','photo postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('photograph','photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('photograph copied','photograph copied');
INSERT INTO itemtypes (itemtype,description) VALUES('photograph negative','photograph negative');
INSERT INTO itemtypes (itemtype,description) VALUES('photograph postcard','photograph postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('photograph, card re-typed.','photograph, card re-typed.');
INSERT INTO itemtypes (itemtype,description) VALUES('photograph- reverse side','photograph- reverse side');
INSERT INTO itemtypes (itemtype,description) VALUES('photograph--post card','photograph--post card');
INSERT INTO itemtypes (itemtype,description) VALUES('post Card','post Card');
INSERT INTO itemtypes (itemtype,description) VALUES('postcard','postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('postcard; blueprint photo (cyanotype)','postcard; blueprint photo (cyanotype)');
INSERT INTO itemtypes (itemtype,description) VALUES('poster','poster');
INSERT INTO itemtypes (itemtype,description) VALUES('print; negative','print; negative');
INSERT INTO itemtypes (itemtype,description) VALUES('semi-glossy photograph','semi-glossy photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('sepia photo postcard','sepia photo postcard');
INSERT INTO itemtypes (itemtype,description) VALUES('sepia photograph','sepia photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('side color','side color');
INSERT INTO itemtypes (itemtype,description) VALUES('sign','sign');
INSERT INTO itemtypes (itemtype,description) VALUES('slde color','slde color');
INSERT INTO itemtypes (itemtype,description) VALUES('slide','slide');
INSERT INTO itemtypes (itemtype,description) VALUES('slide  Color','slide  Color');
INSERT INTO itemtypes (itemtype,description) VALUES('slide  colo','slide  colo');
INSERT INTO itemtypes (itemtype,description) VALUES('slide  color','slide  color');
INSERT INTO itemtypes (itemtype,description) VALUES('slide  oolor','slide  oolor');
INSERT INTO itemtypes (itemtype,description) VALUES('slide 2"x2 "','slide 2"x2 "');
INSERT INTO itemtypes (itemtype,description) VALUES('slide Color','slide Color');
INSERT INTO itemtypes (itemtype,description) VALUES('slide b/w','slide b/w');
INSERT INTO itemtypes (itemtype,description) VALUES('slide cabinet files','slide cabinet files');
INSERT INTO itemtypes (itemtype,description) VALUES('slide cainet files','slide cainet files');
INSERT INTO itemtypes (itemtype,description) VALUES('slide color','slide color');
INSERT INTO itemtypes (itemtype,description) VALUES('slide color #1','slide color #1');
INSERT INTO itemtypes (itemtype,description) VALUES('slide color glass','slide color glass');
INSERT INTO itemtypes (itemtype,description) VALUES('slide colr','slide colr');
INSERT INTO itemtypes (itemtype,description) VALUES('slide coor','slide coor');
INSERT INTO itemtypes (itemtype,description) VALUES('slide glass color','slide glass color');
INSERT INTO itemtypes (itemtype,description) VALUES('slide oolor','slide oolor');
INSERT INTO itemtypes (itemtype,description) VALUES('slidecolor','slidecolor');
INSERT INTO itemtypes (itemtype,description) VALUES('slie  color','slie  color');
INSERT INTO itemtypes (itemtype,description) VALUES('slie color','slie color');
INSERT INTO itemtypes (itemtype,description) VALUES('studio photo','studio photo');
INSERT INTO itemtypes (itemtype,description) VALUES('studio photograph','studio photograph');
INSERT INTO itemtypes (itemtype,description) VALUES('tintype','tintype');
INSERT INTO itemtypes (itemtype,description) VALUES('tintype & oil','tintype & oil');
INSERT INTO itemtypes (itemtype,description) VALUES('unmounted','unmounted');
